var posX;
var posY;
var START_SCREEN = "Welcome to the "
var direction = ["north", "east", "south", "west"];
var floorLevels = ["first", "second", "roof", "sub one", "sub two"];
var areaTypes = ["outdoors", "indoors", "underground"];
var northIndex = direction.indexOf("north");
var eastIndex = direction.indexOf("east");
var southIndex = direction.indexOf("south");
var westIndex = direction.indexOf("west");
var firstIndex = floorLevels.indexOf("first");
var secondIndex = floorLevels.indexOf("second");
var roofIndex = floorLevels.indexOf("roof");
var subOneIndex = floorLevels.indexOf("sub one");
var subTwoIndex = floorLevels.indexOf("sub two");
var outdoorsIndex = areaTypes.indexOf("outdoors");
var indoorsIndex = areaTypes.indexOf("indoors");
var undergroundIndex = areaTypes.indexOf("underground");
const possibleActions = ["read", "examine", "take", "pick up"];
const examineActions = ["look at", "look", "examine"];
const takeActions = ["take", "pick up", "grab"];
const interactions = ["use", "interact"];
var playerBackpack = ["Empty Bottle", "Dry Rag", "Weak Flashlight", "Empty Slot", "Empty Slot", "Empty Slot"];
var readables = ["note"];
var NOTE = "You have been chosen to undergo the trial of the labyrinth we call 'Lost to Time'. \nYou must use your senses, knowledge and instincts to escape. \nThis is a test of your will and of your wisdom. \nYou cannot afford to give up or lose your self control. \nAll will be revealed once you have escaped.";
var north = direction[0];
var east = direction[1];
var south = direction[2];
var west = direction[3];
var first = floorLevels[0];
var second = floorLevels[1];
var roof = floorLevels[2];
var subOne = floorLevels[3];
var subTwo = floorLevels[4];
var outdoors = areaTypes[0];
var indoors = areaTypes[1];
var underground = areaTypes[2];
var floorLevel;
var nextDirection;
var NEXT_DIRECTION_PROMPT = "You can move to another area. \n Will you go north, south, east, west or stay here?";
var changeFloorReq;
var changeFloorAns;
var firstPresence;
var secondPresence;
var roofPresence;
var subOnePresence;
var subTwoPresence;
var falsePresence = "";
var firstQuery = (firstPresence == true||firstPresence == false) ? floorLevels[0]+"\n":falsePresence;
var secondQuery = (secondPresence == true||secondPresence == false) ? floorLevels[1]+"\n":falsePresence;
var roofQuery = (roofPresence == true||roofPresence == false) ? floorLevels[2]+"\n":falsePresence;
var subOneQuery = (subOnePresence == true||subOnePresence == false) ? floorLevels[3]+"\n":falsePresence;
var subTwoQuery = (subTwoPresence == true||subTwoPresence == false) ? floorLevels[4]+"\n":falsePresence;
var CHANGE_FLOOR_REQUEST = "There is another floor here. \n Will you go to another floor? \n Answer with 'Yes' or 'No'";
var CHANGE_FLOOR_PROMPT = "You can go to these levels:\n"+(firstQuery)+(secondQuery)+(roofQuery)+(subOneQuery)+(subTwoQuery)+"Which level do wish to go to?";
var playerAction;
var INTRODUCTION_PROMPT = ("    You awaken in an unfamiliar place, with a compass in hand. There is a small, gray backpack to your right with a handwritten note next to it. You stand and look at what is before you. You are in a dimly lit room, and ahead of you, the only exit to the room you occupy gives way to what you assume to be a maze. You look at your compass, and after reorienting it, understand that the lone exit leads north. \n    You can move to the north, examine the room, or interact with the backpack or read something within the room. \n \n    READ CAREFULLY: To examine something you may enter something like 'Examine' or 'Look at' followed by what you want to examine. To pick up an object you would enter something like 'Pick up' or 'Take' followed by what you want to pick up. And to read from an item inside the room you could enter something like 'Read' or 'Look at' followed by the item you want to read. Using 'Take' on a readable object will give you the text on the readable object and then put it in your backpack. \n\n    You can experiment while you are in the safety of this starting room. \n    Once you are ready to move to the next room, figure out a command to go north.");
var ITEM_INTERACT_PROMPT;
var itemInteracted;
var UNKNOWN_ACTION = "I'm sorry, I don't understand what you mean by '"+(playerAction)+",' what will you do?";
var UNKNOWN_DIRECTION = "I'm sorry, I don't understand what you mean by '"+(nextDirection)+",' will you go north, south, east, west, or stay here?";
var UNKNOWN_FLOOR_QUERY = "I'm sorry, I don't understand what you mean by '"+(changeFloorReq)+",' will you go to another floor?";
var canGoNorth;
var canGoSouth;
var canGoEast;
var canGoWest;
var timeOut;
var roomID = 1300;
var thisRoom;
var UserInput;
var checking;
var compare;
var check;
var takeSmallBoxOutput = "\n\n    You take the small box from the tree hollow and open it. Inside there is a small metal hook. It could probably be used to grab things or to scrape something. You put it into your pocket inventory.";
var playerPockets = ["Empty Slot", "Empty Slot", "Empty Slot", "Empty Slot", "Empty Slot"];
var take;
var checkTake = false;
var gameWin = false;
const beginCommands = ["begin", "start", "go", "now", "move"];
var interact = false;